package plc

const (

	NUMBER_OF_CELLS = 6

	// PATHS
	CODESYS_PATH  = "ns=4;s=|var|CODESYS Control Win V3 x64.Application."
	GVL_PATH      = CODESYS_PATH + "GVL."
	POU_PATH      = CODESYS_PATH + "POU."

	// INPUT WAREHOUSES DATA
	INPUT_WAREHOUSE1_PATH = GVL_PATH + "cin1."
	NODE_ID_INPUTWAREHOUSE_1_ID = INPUT_WAREHOUSE1_PATH + "id"
	NODE_ID_INPUTWAREHOUSE_1_PIECE = INPUT_WAREHOUSE1_PATH + "piece"
	
	INPUT_WAREHOUSE2_PATH = GVL_PATH + "cin2."
	NODE_ID_INPUTWAREHOUSE_2_ID = INPUT_WAREHOUSE2_PATH + "id"
	NODE_ID_INPUTWAREHOUSE_2_PIECE = INPUT_WAREHOUSE2_PATH + "piece"

	INPUT_WAREHOUSE3_PATH = GVL_PATH + "cin3."
	NODE_ID_INPUTWAREHOUSE_3_ID = INPUT_WAREHOUSE3_PATH + "id"
	NODE_ID_INPUTWAREHOUSE_3_PIECE = INPUT_WAREHOUSE3_PATH + "piece"

	INPUT_WAREHOUSE4_PATH = GVL_PATH + "cin4."
	NODE_ID_INPUTWAREHOUSE_4_ID = INPUT_WAREHOUSE4_PATH + "id"
	NODE_ID_INPUTWAREHOUSE_4_PIECE = INPUT_WAREHOUSE4_PATH + "piece"

	// OUTPUT WAREHOUSES DATA
	TOTAL_WAREHOUSES_PATH = GVL_PATH + "total"
	NODE_ID_WAREHOUSE_1_TOTAL = TOTAL_WAREHOUSES_PATH + "1"
	NODE_ID_WAREHOUSE_2_TOTAL = TOTAL_WAREHOUSES_PATH + "2"

	WAREHOUSE1_PATH = GVL_PATH + "W1"
	NODE_ID_WAREHOUSE1_P1_QUANTITY = WAREHOUSE1_PATH + "[1]"
	NODE_ID_WAREHOUSE1_P2_QUANTITY = WAREHOUSE1_PATH + "[2]"
	NODE_ID_WAREHOUSE1_P3_QUANTITY = WAREHOUSE1_PATH + "[3]"
	NODE_ID_WAREHOUSE1_P4_QUANTITY = WAREHOUSE1_PATH + "[4]"
	NODE_ID_WAREHOUSE1_P5_QUANTITY = WAREHOUSE1_PATH + "[5]"
	NODE_ID_WAREHOUSE1_P6_QUANTITY = WAREHOUSE1_PATH + "[6]"
	NODE_ID_WAREHOUSE1_P7_QUANTITY = WAREHOUSE1_PATH + "[7]"
	NODE_ID_WAREHOUSE1_P8_QUANTITY = WAREHOUSE1_PATH + "[8]"
	NODE_ID_WAREHOUSE1_P9_QUANTITY = WAREHOUSE1_PATH + "[9]"

	WAREHOUSE2_PATH = GVL_PATH + "W2"
	NODE_ID_WAREHOUSE2_P1_QUANTITY = WAREHOUSE2_PATH + "[1]"
	NODE_ID_WAREHOUSE2_P2_QUANTITY = WAREHOUSE2_PATH + "[2]"
	NODE_ID_WAREHOUSE2_P3_QUANTITY = WAREHOUSE2_PATH + "[3]"
	NODE_ID_WAREHOUSE2_P4_QUANTITY = WAREHOUSE2_PATH + "[4]"
	NODE_ID_WAREHOUSE2_P5_QUANTITY = WAREHOUSE2_PATH + "[5]"
	NODE_ID_WAREHOUSE2_P6_QUANTITY = WAREHOUSE2_PATH + "[6]"
	NODE_ID_WAREHOUSE2_P7_QUANTITY = WAREHOUSE2_PATH + "[7]"
	NODE_ID_WAREHOUSE2_P8_QUANTITY = WAREHOUSE2_PATH + "[8]"
	NODE_ID_WAREHOUSE2_P9_QUANTITY = WAREHOUSE2_PATH + "[9]"

	// CELL DATA
	CELLS_PATH = GVL_PATH + "cell" 	
	CELL1_PATH = CELLS_PATH + "1."
	CELL2_PATH = CELLS_PATH + "2."
	CELL3_PATH = CELLS_PATH + "3."
	CELL4_PATH = CELLS_PATH + "4."
	CELL5_PATH = CELLS_PATH + "5."
	CELL6_PATH = CELLS_PATH + "6."

	NODE_ID_CELL1_ID = CELL1_PATH + "id"
	NODE_ID_CELL1_PIECE = CELL1_PATH + "piece"
	NODE_ID_CELL1_PROCESSBOT = CELL1_PATH + "processBot"
	NODE_ID_CELL1_PROCESSTOP = CELL1_PATH + "processTop"
	NODE_ID_CELL1_TOOLBOT = CELL1_PATH + "tool_MBot"
	NODE_ID_CELL1_TOOLTOP = CELL1_PATH + "tool_MTop"

	NODE_ID_CELL2_ID = CELL2_PATH + "id"
	NODE_ID_CELL2_PIECE = CELL2_PATH + "piece"
	NODE_ID_CELL2_PROCESSBOT = CELL2_PATH + "processBot"
	NODE_ID_CELL2_PROCESSTOP = CELL2_PATH + "processTop"
	NODE_ID_CELL2_TOOLBOT = CELL2_PATH + "tool_MBot"
	NODE_ID_CELL2_TOOLTOP = CELL2_PATH + "tool_MTop"

	NODE_ID_CELL3_ID = CELL3_PATH + "id"
	NODE_ID_CELL3_PIECE = CELL3_PATH + "piece"
	NODE_ID_CELL3_PROCESSBOT = CELL3_PATH + "processBot"
	NODE_ID_CELL3_PROCESSTOP = CELL3_PATH + "processTop"
	NODE_ID_CELL3_TOOLBOT = CELL3_PATH + "tool_MBot"
	NODE_ID_CELL3_TOOLTOP = CELL3_PATH + "tool_MTop"

	NODE_ID_CELL4_ID = CELL4_PATH + "id"
	NODE_ID_CELL4_PIECE = CELL4_PATH + "piece"
	NODE_ID_CELL4_PROCESSBOT = CELL4_PATH + "processBot"
	NODE_ID_CELL4_PROCESSTOP = CELL4_PATH + "processTop"
	NODE_ID_CELL4_TOOLBOT = CELL4_PATH + "tool_MBot"
	NODE_ID_CELL4_TOOLTOP = CELL4_PATH + "tool_MTop"

	NODE_ID_CELL5_ID = CELL5_PATH + "id"
	NODE_ID_CELL5_PIECE = CELL5_PATH + "piece"
	NODE_ID_CELL5_PROCESSBOT = CELL5_PATH + "processBot"
	NODE_ID_CELL5_PROCESSTOP = CELL5_PATH + "processTop"
	NODE_ID_CELL5_TOOLBOT = CELL5_PATH + "tool_MBot"
	NODE_ID_CELL5_TOOLTOP = CELL5_PATH + "tool_MTop"

	NODE_ID_CELL6_ID = CELL6_PATH + "id"
	NODE_ID_CELL6_PIECE = CELL6_PATH + "piece"
	NODE_ID_CELL6_PROCESSBOT = CELL6_PATH + "processBot"
	NODE_ID_CELL6_PROCESSTOP = CELL6_PATH + "processTop"
	NODE_ID_CELL6_TOOLBOT = CELL6_PATH + "tool_MBot"
	NODE_ID_CELL6_TOOLTOP = CELL6_PATH + "tool_MTop"

	//CELL CONTROL DATA
	CELLS_CONTROL_PATH = POU_PATH + "id"
	NODE_ID_CELL1_CONTROL_IN_PATH = CELLS_CONTROL_PATH + "1_i"
	NODE_ID_CELL1_CONTROL_OUT_PATH = CELLS_CONTROL_PATH + "1_o"

	NODE_ID_CELL2_CONTROL_IN_PATH = CELLS_CONTROL_PATH + "2_i"
	NODE_ID_CELL2_CONTROL_OUT_PATH = CELLS_CONTROL_PATH + "2_o"

	NODE_ID_CELL3_CONTROL_IN_PATH = CELLS_CONTROL_PATH + "3_i"
	NODE_ID_CELL3_CONTROL_OUT_PATH = CELLS_CONTROL_PATH + "3_o"

	NODE_ID_CELL4_CONTROL_IN_PATH = CELLS_CONTROL_PATH + "4_i"
	NODE_ID_CELL4_CONTROL_OUT_PATH = CELLS_CONTROL_PATH + "4_o"

	NODE_ID_CELL5_CONTROL_IN_PATH = CELLS_CONTROL_PATH + "5_i"
	NODE_ID_CELL5_CONTROL_OUT_PATH = CELLS_CONTROL_PATH + "5_o"

	NODE_ID_CELL6_CONTROL_IN_PATH = CELLS_CONTROL_PATH + "6_i"
	NODE_ID_CELL6_CONTROL_OUT_PATH = CELLS_CONTROL_PATH + "6_o"
)



type Place_holder_cell_struct struct {
	Index      OpcuaInt16
	Piece      OpcuaInt16
	ProcessBot OpcuaBool
	ProcessTop OpcuaBool
	ToolBot    OpcuaInt16
	ToolTop    OpcuaInt16
}

// Contains the opcua variale for ID of the last processed command for a line
type Place_holder_cell_control struct {
	NewPieceID OpcuaInt16 // id of the piece that entered the line from W1
	OutPieceID OpcuaInt16 // id of the piece that left the line to W2
}

type Place_holder_InputWarehouses struct {
	TxID  OpcuaInt16
	Piece OpcuaInt16
}

type Place_holder_Warehouses struct {
	Quantity   OpcuaInt16
	QuantityP1 OpcuaInt16
	QuantityP2 OpcuaInt16
	QuantityP3 OpcuaInt16
	QuantityP4 OpcuaInt16
	QuantityP5 OpcuaInt16
	QuantityP6 OpcuaInt16
	QuantityP7 OpcuaInt16
	QuantityP8 OpcuaInt16
	QuantityP9 OpcuaInt16
}


